const nominaTiposDeducciones: Record<string, string> = {
  '001': 'Seguridad social',
  '002': 'ISR',
  '003': 'Aportaciones a retiro, cesantía en edad avanzada y vejez.',
  '004': 'Otros',
  '005': 'Aportaciones a Fondo de vivienda',
  '006': 'Descuento por incapacidad',
  '007': 'Pensión alimenticia',
  '008': 'Renta',
  '009': 'Préstamos provenientes del Fondo Nacional de la Vivienda para los Trabajadores',
  '010': 'Pago por crédito de vivienda',
  '011': 'Pago de abonos INFONACOT',
  '012': 'Anticipo de salarios',
  '013': 'Pagos hechos con exceso al trabajador',
  '014': 'Errores',
  '015': 'Pérdidas',
  '016': 'Averías',
  '017': 'Adquisición de artículos producidos por la empresa o establecimiento',
  '018': 'Cuotas para la constitución y fomento de sociedades cooperativas y de cajas de ahorro',
  '019': 'Cuotas sindicales',
  '020': 'Ausencia (Ausentismo)',
  '021': 'Cuotas obrero patronales',
  '022': 'Impuestos Locales',
  '023': 'Aportaciones voluntarias',
  '024': 'Ajuste en Gratificación Anual (Aguinaldo) Gravado',
  '025': 'Ajuste en Gratificación Anual (Aguinaldo) Exento',
  '026': 'Ajuste en Participación de los Trabajadores en las Utilidades PTU Gravado',
  '027': 'Ajuste en Participación de los Trabajadores en las Utilidades PTU Exento',
  '028': 'Ajuste en Reembolso de Gastos Médicos Dentales y Hospitalarios Exento',
  '029': 'Ajuste en Fondo de ahorro Exento',
  '030': 'Ajuste en Caja de ahorro Exento',
  '031': 'Ajuste en contribuciones a cargo del trabajador pagadas por el patrón Exento',
  '032': 'Ajuste en Premios por puntualidad Gravado',
  '033': 'Ajuste en Prima de Seguro de vida Exento',
  '034': 'Ajuste en Seguro de Gastos Médicos Mayores Exento',
  '035': 'Ajuste en Cuotas Sindicales Pagadas por el Patrón Exento',
  '036': 'Ajuste en Subsidios por incapacidad Exento',
  '037': 'Ajuste en Becas para trabajadores y/o hijos Exento',
  '038': 'Ajuste en horas extra Exento',
  '039': 'Ajuste en Prima dominical Exento',
  '040': 'Ajuste en Prima vacacional Gravado',
  '041': 'Ajuste en Prima vacacional Exento',
  '042': 'Ajuste en Prima por antigüedad Gravado',
  '043': 'Ajuste en Pagos por separación Gravado',
  '044': 'Ajuste en Pagos por separación Exento',
  '045': 'Ajuste en Seguro de retiro Exento',
  '046': 'Ajuste en Indemnizaciones Gravado',
  '047': 'Ajuste en Indemnizaciones Exento',
  '048': 'Ajuste en Reembolso por funeral Exento',
  '049': 'Ajuste en Cuotas de seguridad social pagadas por el patrón Exento',
  '050': 'Ajuste en Aportaciones al sistema para el retiro Exento',
  '051': 'Ajuste en Aportaciones a fondo de vivienda Exento',
  '052': 'Ajuste en Ayuda por renta Exento',
  '053': 'Ajuste en Ayuda artículos escolares Exento',
  '054': 'Ajuste en Ayuda anteojos Exento',
  '055': 'Ajuste en Ayuda transporte Exento',
  '056': 'Ajuste en Ayuda gastos de funeral Exento',
  '057': 'Ajuste en Otros ingresos por salarios Gravado',
  '058': 'Ajuste en Otros ingresos por salarios Exento',
  '059': 'Ajuste en Jubilaciones, pensiones o haberes de retiro en una exhibición Gravado',
  '060': 'Ajuste en Jubilaciones, pensiones o haberes de retiro en parcialidades Gravado',
  '061': 'Ajuste en Jubilaciones, pensiones o haberes de retiro en una exhibición Exento.',
  '062': 'Ajuste en Jubilaciones, pensiones o haberes de retiro en parcialidades Exento.',
  '063': 'Ajuste en Subsidio para el empleo (efectivamente entregado al trabajador).',
  '064': 'Ajuste en Ingresos en acciones o títulos valor que representan bienes Gravado',
  '065': 'Ajuste en Ingresos en acciones o títulos valor que representan bienes Exento',
  '066': 'Ajuste en ingresos asimilados a salarios Gravados',
  '067': 'Ajuste en Bonos, Despensas',
  '068': 'Ajuste en sueldos y salarios',
  '069': 'Ajuste en jubilaciones, pensiones o haberes de retiro',
  '070':
    'Ajuste en provisión de pagos de pensión en parcialidades derivado de Jubilaciones, Pensiones o Haberes de Retiro',
  '071': 'Ajuste en pagos por separación acumulable',
  '072': 'Ajuste en pagos por separación no acumulable',
  '073': 'Ajuste al salario bruto por ISR de pagos por separación',
  '074': 'Ajuste al subsidio causado',
  '075': 'Ajuste en Viáticos gravados',
  '076': 'Ajuste a pagos asimilados a salarios gravados',
  '077': 'Ajuste en Viáticos exentos',
  '078': 'Ajuste en Ingresos por acciones o títulos valor que representan bienes - acumulable',
  '079': 'Ajuste en Ingresos por acciones o títulos valor que representan bienes - no acumulable',
  '080':
    'Ajuste en Subsidio Efectivamente Entregado que no correspondía (Aplica solo cuando haya transcurrido el ejercicio fiscal).',
  '081': 'Ajuste en Cuotas obrero patronales',
  '082': 'Ajuste en impuestos locales',
  '083': 'Ajuste a pagos asimilados a salarios exentos',
  '084': 'Ajuste a Pago por Servicios Profesionales',
  '085': 'Ajuste a Pago a Consejeros',
  '086': 'Ajuste a Pago Actividades Empresariales',
  '087': 'Ajuste a Pagos a Otros Asimilados',
  '088': 'Ajuste a Pagos por Honorarios a Personas Morales',
  '089': 'Ajuste a Pagos por Rendimientos a Miembros de Cooperativas, Sociedades y Asociaciones Civiles',
  '090': 'Ajuste a Ingresos Asimilados a Salarios Exentos',
  '091': 'Reintegro por error en pagos asimilados',
  '092': 'Reintegro por error en sueldos y salarios',
  '093': 'Reintegro por error en jubilaciones',
  '094': 'Reintegro por error en pagos por separación',
  '095': 'Devolución de descuentos efectuados para el crédito de vivienda',
  '098': 'Pago de PTU',
  '099': 'Otros',
};

export const findTipoDeduccionTexto = (id: string): string => {
  return nominaTiposDeducciones[id] ?? '';
};

export default nominaTiposDeducciones;
